---
global:
  scrape_interval: 3s

scrape_configs:
  - job_name: idmsvc_backend
    static_configs:
      - targets:
          - host.containers.internal:9000
          - host.docker.internal:9000
          - localhost:9000
